apiVersion: 1

datasources:
  - name: grafana-postgresql-safety_eye
    uid: safety-eye-postgres
    type: postgres
    url: postgres:5432
    database: safety_eye
    user: postgres
    secureJsonData:
      password: "${DB_PASSWORD}"
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
