name: Bug report
description: Report a reproducible problem in SafetyEye.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run command ...
        2. Open ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Error output
      description: Paste the relevant terminal/log output.
      render: shell
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: Windows 11 / Ubuntu 22.04 / macOS 14
  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "3.11.9"
